config/routes.rb
Rails.application.routes.draw do
  get 'posts', to: 'posts#index'
  get 'static_pages/new'
  root 'posts#index'  
  devise_for :users
  get '/pending', to: 'users#pending'
  resources :users, only: [:show, :index, :update]
  resources :relationships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :pictures, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  after_save   :make_timeline_record 
  after_destroy :destroy_post_timeline
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 5000 }
  
  private
  
    def make_timeline_record
      Timeline.create!(user_id: self.user.id, post_id: self.id)
    end
    
    def destroy_post_timeline
      Timeline.delete_timeline(self.user, self)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = current_user.timeline.paginate(page: params[:page])
    @post = current_user.posts.build
    @picture = current_user.pictures.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post Saved!"
      redirect_back(fallback_location: posts_path)
    else
      flash[:notice] = "Unable to Save Post"
      redirect_back(fallback_location: posts_path)
    end
  end
  
  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_back(fallback_location: posts_path)
  end
  
  private

    def post_params
      params.require(:post).permit(:content)
    end  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like_form.html.erb
<%= form_for(current_user.likes.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :likeable_id, post.id %></div>
  <div><%= hidden_field_tag :likeable_type, "#{post.class.to_s}" %></div>  
  <%= f.submit yield(:add_like_text), class: "btn btn-primary" %>
<% end %>

app/views/posts/_picture.html.erb
<li id="picture-<%= picture.id %>">
  <span class="user"><%= link_to picture.user.username, picture.user %> - 
  <%= pluralize(picture.likes.count, "like") %></span>
  
  <span class="content"><%= image_tag picture.image.url(:medium) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(picture.created_at) %> ago.
  <% if current_user == picture.user %>
    <%= link_to "delete", picture, method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
  </span>
  <span class="like_buttons">
  <% if current_user.post_liked?(picture) %>
    <%= render 'posts/unlike_form', post: picture %>
  <% else %>
    <%=  render 'posts/like_form', post: picture %>
  <% end %>
  </span>
  
  <span class="comments">
    <span class ="comment_count">Post has <%= pluralize( picture.comments.count, "comment") %><br />
    <span class="comment"><%= render picture.comments %></span>
  </span>
  
  <span class="comment_form"><%= render 'comments/comment_form', post: picture %></span>
  
</li>

app/views/posts/_picture_form.html.erb
<%= form_for @picture, url: pictures_path, html: { multipart: true } do |form| %>
  <%= form.file_field :image %>
  <%= form.submit "Post" %>
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.username, post.user %> - 
  <%= pluralize(post.likes.count, "like") %></span>
  
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  <% if current_user == post.user %>
    <%= link_to "delete", post, method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
  </span>
  <span class="like_buttons">
  <% if current_user.post_liked?(post) %>
    <%= render 'posts/unlike_form', post: post %>
  <% else %>
    <%=  render 'posts/like_form', post: post %>
  <% end %>
  </span>
  
  <span class="comments">
    <span class ="comment_count">Post has <%= pluralize( post.comments.count, "comment") %><br />
    <span class="comment"><%= render post.comments %></span>
  </span>
  
  <span class="comment_form"><%= render 'comments/comment_form', post: post %></span>
  
</li>

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/_posts.html.erb
<% @posts.each do | post | %>
  <% if post.picture_id.nil? %>
    <% current_post = Post.find(post.post_id) %>
    <%= render 'posts/post', post: current_post %>
  <% else %>
    <% current_pic = Picture.find(post.picture_id) %>
    <%= render 'posts/picture', picture: current_pic %>
  <% end %>
<% end %>

app/views/posts/_timeline.html.erb
<% if timeline.picture_id.nil? %>
  <%= render 'post' %>
<% end %>

app/views/posts/_unlike_form.html.erb
<% like = current_user.find_like(post).first %>
<%= form_for(like,
             html: { method: :delete }) do |f| %>
  <div><%= hidden_field_tag :like_id, like.id %></div>
  <%= f.submit yield(:delete_like_text), class: "btn btn-primary" %>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, 'Your Timeline') %>
<% provide(:add_like_text, 'Like Post') %>
<% provide(:delete_like_text, 'Unlike Post') %>

<h1>Welcome, <%= current_user.username  %>!</h1>

<%= render 'post_form'  %><br/ >

<h3>Post a Picture</h3>
<%= render 'picture_form'  %>

<%= will_paginate %>

<ul class="posts">
  <%= render 'posts' %>
</ul>

<%= will_paginate %>