config/routes.rb
Rails.application.routes.draw do
  get 'posts', to: 'posts#index'
  get 'static_pages/new'
  root 'posts#index'  
  devise_for :users
  get '/pending', to: 'users#pending'
  resources :users, only: [:show, :index, :update]
  resources :relationships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :pictures, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "OFB", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
          <% if current_user.has_pending_requests? %>
            <li><%= link_to "NEW FRIENDS!", pending_path %></li>
          <% end %>
        <li><%= link_to "Home", posts_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Users", users_path %></li>
              <li><%= link_to "My Profile", current_user %></li>
              <li><%= link_to "My Timeline", posts_path %></li>
              <li><%= link_to "Settings", edit_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>  
      </ul>
    <% end %>  
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>